### ISSUE TITLE
BUILD FAILED 'Ld build/Debug-iphoneos/my.app/my normal armv7'

### ISSUE THREAD

**Issue by McDo** [benbahrenburg/Ti.BlurView#13]
I'm using bencoding.blur-iphone-0.35 with my alloy based project, and got an error when compiling and installing the app on my iphone5C. here is the error log:

[ERROR] :  *\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/Debug-iphoneos/myapp.app/myapp normal armv7
[ERROR] :  (1 failure)

Here is my building environment: 
- titanium SDK: 3.2.3.GA
- alloy: 1.3.1
- xcode: 5.1.1
- osx: 10.9.2

Testing environment:
- iphone5C: running iOS 7.1.1

Any idea?

**Comment by axmo** [comment]
More info on this, in case anyone else is having the same problem:

The titanium build system does not link any classes that are not referenced in your javascript, which causes this error, if you don't happen to use a standard Ti.UI.ImageView anywhere else in your app.

Add ``` var unused = Ti.UI.createImageView(); ``` somewhere in your app, and it suddenly compiles.  It seems like there SHOULD be a way to fix this in the module, so I would call this either a Titanium bug or a bug in this module, not sure which, though.

see https://jira.appcelerator.org/browse/TC-1908 for more info

**Comment by iotashan** [comment]
There's a better way, will do a PR soon.

**Comment by iotashan** [comment]
Take out your `var unused` hack, and try the builds I just created. They should do the trick, thanks to the manifest.json files I added.

https://github.com/iotashan/Ti.BlurView

If they work for you, I'll submit the PR.
