### ISSUE TITLE
Script Error Couldn't find module: bencding.blur for architecture: x86_64

### ISSUE THREAD

**Issue by Max87ZA** [benbahrenburg/Ti.BlurView#21]
Hi Ben,
after I installed this module from gittio(v0.37) and later by myself from dist folder(v0.41beta) it throws me this error. Can you please help me how to fix it? Thank you

**Comment by benbahrenburg** [comment]
Can't reproduce, please clean your project. If you are still running into problems you can download and build from source.

**Comment by Max87ZA** [comment]
I don't understand...I build module from source via xcode and CLI and overwrite existing files in my project's modules folder, clean project from Studio and run in simulator/device - same error. If I try xcrun lipo -info libbencoding.blur.a, it shows me available platforms and x86_64 and arm64 are there...Same for version 0.37 installed from gittio.
Can you please help me what to do?
Thank you

**Comment by benbahrenburg** [comment]
Sorry, as I can't recreate there isn't much help I can provide. I would suggest targetting the latest Ti SDK nightly build perhaps that will fix the problem you are encountering.  You can also open a support ticket with Appcelerator depending on your plan.  As you mentioned the issue you are encountering isn't related to the module but something in your build process.
